name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decrypt fonts
        env:
          FONT_ARCHIVE_PASSPHRASE: ${{ secrets.FONT_ARCHIVE_PASSPHRASE }}
        run: |
          openssl enc -d -aes-256-cbc -pbkdf2 \
            -in fonts.tar.xz.enc -out fonts.tar.xz \
            -pass env:FONT_ARCHIVE_PASSPHRASE
          tar -xJf fonts.tar.xz
          rm fonts.tar.xz

 
      - name: Build with TeX Live (lualatex)
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            chmod +x build.sh
            ./build.sh "${{ github.event.release.tag_name }}"

      - name: Remove decrypted fonts
        if: always()
        run: rm -rf ./Fonts

      - name: Attach zip to the release
        uses: softprops/action-gh-release@v2
        with:
          files: build/ugentdocs-${{ github.event.release.tag_name }}.zip
